[package]
name = "cfg"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Control flow graph analysis and Arm64 opcode classification"

[dependencies]
yaxpeax-arm.workspace = true
petgraph.workspace = true
lazy_static = "1.4"